name = "onboarding-worker"
main = "src/index.ts"
compatibility_date = "2024-11-21"

[vars]
ENVIRONMENT = "development"
JWT_SECRET = "development-secret-key-change-in-production"

[[kv_namespaces]]
binding = "ONBOARDING_KV"
id = "d3a7f6980ac440a08f9bf75bb5542c0d"