name = "onboarding-worker"
main = "src/index.ts"
compatibility_date = "2024-11-21"

[vars]
ENVIRONMENT = "development"

[[kv_namespaces]]
binding = "ONBOARDING_KV"
id = "placeholder"
preview_id = "placeholder"

[[durable_objects.bindings]]
name = "USER_SESSION"
class_name = "UserSession"